import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Nav'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Navbar />


      <main>
        <h1 className={styles.title}>
          Welcome to Next.js!
        </h1>

        <p >
        secretOrPrivateKey is a string, buffer, or object containing either the secret for HMAC algorithms or the PEM encoded private key for RSA and ECDSA. In case of a private key with passphrase an object key, passphrase  can be used (based on crypto documentation), in this case be sure you pass the algorithm option.
        </p>

      
      </main>

      <footer className={styles.footer}>
      Powered by: Just Bazz
      </footer>
    </div>
  )
}
